<?php

namespace App\Http\Middleware;

use Closure;

class CustomTrimStrings extends TrimStrings
{
    public function handle($request, Closure $next, ...$attributes)
    {
        $this->except = array_merge($this->except, (array) $request->get('_white_space_', []));
        return parent::handle($request, $next, $attributes); // TODO: Change the autogenerated stub
    }
}
